### PR TITLE
[~][ci skip](Updated) `install_opengl.ps1`

### PR DESCRIPTION
**Pull request by Xemorph**
The linker under Windows is also looking for the `glfw3.lib` file.
I just added the `move` command for this file.

### CODE REVIEW

**Comment by VoltanaDMG** [comment]
Hmm, looks fine but we need a check for the new `move` command so that CI pipeline won't crash at this preinstall script.

**Comment by Xemorph** [comment]
Okay, let me fix it shortly. I'm going to notify you, @VoltanaDMG , if the test was successfull.
Also, thanks for the fast response.

**Review by VoltanaDMG — CHANGES_REQUESTED** [review]
Please add another check for the new `move` command. We should really catch those errors!

**Comment by Xemorph** [comment]
I made some multiple changes.
- Renamed `$filepath` to `$filepathDll`
- Changed if `Test-Path ...` to `Test-Path ... -and Test-Path ...`

In the next version we should take look to get out the `UnauthorizedAccessException`.
Currently, we need to run this script `As Administrator`...

**Comment by VoltanaDMG** [comment]
Yeah, should take a look for the next version why we get this error under windows. But don't forget in `AppVeyor` we have administrative rights and there we don't get any `UnauthorizedAccessException`.

I'm not happy with the `-y` switch, cause it should not be necessary. We are removing the old files and the script should run without any errors. But for now, it is fine.

**Review by VoltanaDMG — APPROVED** [review]

**Comment by VoltanaDMG** [comment]
Okay, is merged now. I'm gonna close this conversation. There aren't any changes to do for this commit.

**Pull request merged**
